# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server.proto import notify_pb2 as notify__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notify_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotifyServiceStub(object):
    """One simple domain event: an order status changed.
    gRPC is great for this internal service-to-service call because:
    - schema is enforced (proto3 types, not freeform JSON)
    - binary serialisation is faster than JSON
    - the client stub is generated — no hand-rolled HTTP calls

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNotification = channel.unary_unary(
                '/notify.NotifyService/SendNotification',
                request_serializer=notify__pb2.NotifyRequest.SerializeToString,
                response_deserializer=notify__pb2.NotifyResponse.FromString,
                _registered_method=True)
        self.StreamNotifications = channel.unary_stream(
                '/notify.NotifyService/StreamNotifications',
                request_serializer=notify__pb2.StreamRequest.SerializeToString,
                response_deserializer=notify__pb2.NotifyResponse.FromString,
                _registered_method=True)


class NotifyServiceServicer(object):
    """One simple domain event: an order status changed.
    gRPC is great for this internal service-to-service call because:
    - schema is enforced (proto3 types, not freeform JSON)
    - binary serialisation is faster than JSON
    - the client stub is generated — no hand-rolled HTTP calls

    """

    def SendNotification(self, request, context):
        """Unary RPC — same request/response shape as REST but over HTTP/2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNotifications(self, request, context):
        """Server-streaming RPC — server pushes multiple responses for one request
        Mirrors what WebSocket does but with enforced types
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=notify__pb2.NotifyRequest.FromString,
                    response_serializer=notify__pb2.NotifyResponse.SerializeToString,
            ),
            'StreamNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNotifications,
                    request_deserializer=notify__pb2.StreamRequest.FromString,
                    response_serializer=notify__pb2.NotifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notify.NotifyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notify.NotifyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotifyService(object):
    """One simple domain event: an order status changed.
    gRPC is great for this internal service-to-service call because:
    - schema is enforced (proto3 types, not freeform JSON)
    - binary serialisation is faster than JSON
    - the client stub is generated — no hand-rolled HTTP calls

    """

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notify.NotifyService/SendNotification',
            notify__pb2.NotifyRequest.SerializeToString,
            notify__pb2.NotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/notify.NotifyService/StreamNotifications',
            notify__pb2.StreamRequest.SerializeToString,
            notify__pb2.NotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
