# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notify.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnotify.proto\x12\x06notify\"B\n\rNotifyRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"1\n\x0eNotifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"&\n\rStreamRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t2\x9a\x01\n\rNotifyService\x12\x41\n\x10SendNotification\x12\x15.notify.NotifyRequest\x1a\x16.notify.NotifyResponse\x12\x46\n\x13StreamNotifications\x12\x15.notify.StreamRequest\x1a\x16.notify.NotifyResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYREQUEST']._serialized_start=24
  _globals['_NOTIFYREQUEST']._serialized_end=90
  _globals['_NOTIFYRESPONSE']._serialized_start=92
  _globals['_NOTIFYRESPONSE']._serialized_end=141
  _globals['_STREAMREQUEST']._serialized_start=143
  _globals['_STREAMREQUEST']._serialized_end=181
  _globals['_NOTIFYSERVICE']._serialized_start=184
  _globals['_NOTIFYSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
