[project]
name = "basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Assefa Tesfay", email = "asefatesfay@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bedrock-agentcore>=1.22.0",
    "bedrock-agentcore-starter-toolkit>=0.3.12",
    "boto3>=1.43.78",
    "requests>=2.34.2",
    "strands-agents>=1.53.0",
]

[project.scripts]
basics = "basics:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
